/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppModal {
        "url": string;
    }
    interface AppPeopleDetail {
        "personId": number;
    }
    interface AppRoot {
    }
    interface AppTabs {
    }
    interface CatProfile {
        "description": string;
        "name": string;
        "title": string;
    }
    interface PageHome {
    }
    interface PageNotice {
    }
    interface PageProfile {
        "name": string;
    }
}
declare global {
    interface HTMLAppModalElement extends Components.AppModal, HTMLStencilElement {
    }
    var HTMLAppModalElement: {
        prototype: HTMLAppModalElement;
        new (): HTMLAppModalElement;
    };
    interface HTMLAppPeopleDetailElement extends Components.AppPeopleDetail, HTMLStencilElement {
    }
    var HTMLAppPeopleDetailElement: {
        prototype: HTMLAppPeopleDetailElement;
        new (): HTMLAppPeopleDetailElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppTabsElement extends Components.AppTabs, HTMLStencilElement {
    }
    var HTMLAppTabsElement: {
        prototype: HTMLAppTabsElement;
        new (): HTMLAppTabsElement;
    };
    interface HTMLCatProfileElement extends Components.CatProfile, HTMLStencilElement {
    }
    var HTMLCatProfileElement: {
        prototype: HTMLCatProfileElement;
        new (): HTMLCatProfileElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageNoticeElement extends Components.PageNotice, HTMLStencilElement {
    }
    var HTMLPageNoticeElement: {
        prototype: HTMLPageNoticeElement;
        new (): HTMLPageNoticeElement;
    };
    interface HTMLPageProfileElement extends Components.PageProfile, HTMLStencilElement {
    }
    var HTMLPageProfileElement: {
        prototype: HTMLPageProfileElement;
        new (): HTMLPageProfileElement;
    };
    interface HTMLElementTagNameMap {
        "app-modal": HTMLAppModalElement;
        "app-people-detail": HTMLAppPeopleDetailElement;
        "app-root": HTMLAppRootElement;
        "app-tabs": HTMLAppTabsElement;
        "cat-profile": HTMLCatProfileElement;
        "page-home": HTMLPageHomeElement;
        "page-notice": HTMLPageNoticeElement;
        "page-profile": HTMLPageProfileElement;
    }
}
declare namespace LocalJSX {
    interface AppModal {
        "url"?: string;
    }
    interface AppPeopleDetail {
        "personId"?: number;
    }
    interface AppRoot {
    }
    interface AppTabs {
    }
    interface CatProfile {
        "description"?: string;
        "name"?: string;
        "title"?: string;
    }
    interface PageHome {
    }
    interface PageNotice {
    }
    interface PageProfile {
        "name"?: string;
    }
    interface IntrinsicElements {
        "app-modal": AppModal;
        "app-people-detail": AppPeopleDetail;
        "app-root": AppRoot;
        "app-tabs": AppTabs;
        "cat-profile": CatProfile;
        "page-home": PageHome;
        "page-notice": PageNotice;
        "page-profile": PageProfile;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-modal": LocalJSX.AppModal & JSXBase.HTMLAttributes<HTMLAppModalElement>;
            "app-people-detail": LocalJSX.AppPeopleDetail & JSXBase.HTMLAttributes<HTMLAppPeopleDetailElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-tabs": LocalJSX.AppTabs & JSXBase.HTMLAttributes<HTMLAppTabsElement>;
            "cat-profile": LocalJSX.CatProfile & JSXBase.HTMLAttributes<HTMLCatProfileElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-notice": LocalJSX.PageNotice & JSXBase.HTMLAttributes<HTMLPageNoticeElement>;
            "page-profile": LocalJSX.PageProfile & JSXBase.HTMLAttributes<HTMLPageProfileElement>;
        }
    }
}
